name: ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: [ "/dist" ]
  pull_request:
    branches: [ main ]
    paths: [ "/dist" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@main

      - name: Push to Public Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: public
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

