name: ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: [ "dist/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "dist/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-deploy:
    name: Build Gatsby Project and Deploy to Hostinger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build --if-present

      - name: Push to Public Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: public
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

